// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpRSDvU-JZQdrGK4zT5cMCN_3TLNRH7s',
    appId: '1:281825950573:web:fe44479718b84356bd3864',
    messagingSenderId: '281825950573',
    projectId: 'to-do-list-e556e',
    authDomain: 'to-do-list-e556e.firebaseapp.com',
    databaseURL: 'https://to-do-list-e556e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-e556e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDIOKdiYOAHvaMx4_p41IuerJqyNw8jA',
    appId: '1:281825950573:android:8ec04c21f0e4773fbd3864',
    messagingSenderId: '281825950573',
    projectId: 'to-do-list-e556e',
    databaseURL: 'https://to-do-list-e556e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-e556e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLX3cgWZc5co4yLXiT_lgOJDLZAzRbUrU',
    appId: '1:281825950573:ios:545145a0aa474a01bd3864',
    messagingSenderId: '281825950573',
    projectId: 'to-do-list-e556e',
    databaseURL: 'https://to-do-list-e556e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-list-e556e.appspot.com',
    iosClientId: '281825950573-s8t48kk9t085v4ha1259f88lrj3fc2g2.apps.googleusercontent.com',
    iosBundleId: 'com.todolistlukaszios',
  );
}
